AWSTemplateFormatVersion: '2010-09-09'
Description: Hello World Lambda function with public Function URL

Resources:
  HelloWorldFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  HelloWorldFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: HelloWorldFunction
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt HelloWorldFunctionRole.Arn
      MemorySize: 128
      Timeout: 10
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              """
              Lambda function that responds with Hello World!
              Triggered via Function URL with GET request
              """
              return {
                  'statusCode': 200,
                  'headers': {
                      'Content-Type': 'text/plain',
                      'Access-Control-Allow-Origin': '*'
                  },
                  'body': 'Hello World!!'
              }

  HelloWorldFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt HelloWorldFunction.Arn
      Cors:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
        AllowHeaders:
          - "*"

  HelloWorldFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref HelloWorldFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

Outputs:
  HelloWorldFunctionUrl:
    Description: "Function URL for Hello World Lambda"
    Value: !GetAtt HelloWorldFunctionUrl.FunctionUrl
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
